Mugy's changes
zolboo-gtn/time_management_backend pull request #5
Opened 2022-08-25 03:19 UTC by munkhgerel-gtn

* prisma udpate
* attendance request endpoints
* attendance endoints
* owner guard
* changes database schema

2022-09-06 06:40 UTC, zolboo-gtn requested changes

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/app/app.module.ts
>  import { MiddlewareConsumer, Module, NestModule } from "@nestjs/common";
basi_auth болгох

2022-09-06 06:40 UTC, zolboo-gtn commented on prisma/schema.prisma
> +  status    AttendanceStatus @default(APPROVED)
default: PENDING

2022-09-06 06:40 UTC, zolboo-gtn commented on prisma/schema.prisma
> +  isNormal  Boolean           @default(true)
шаардлагатай эсэх?

2022-09-06 06:40 UTC, zolboo-gtn commented on src/common/interfaces/request_with_user.interface.ts
> +  user: User;
entity хэрэглэх?

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
> +    const beforeStarted = await this.prisma.attendance.findFirst({
isStarted?

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
> +const STARTHOUR: number = 16; // timeZone +8 үед 16 цаг нь 24 цагтай тэнцэнэ.
timezone ашиглах?

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
> +    items.map(async (item) => {
for loop ашиглах for in, for of, for

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/dtos/send_request.dto.ts
> +  @Matches(/^(HOLIDAY|DAYOFF|SICK)$/, {
enum TYPE

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/dtos/send_request.dto.ts
> +  @Matches(/^(APPROVED|DECLINED)$/, {
enum STATUS

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/auth/strategies/basic.strategy.ts
> +import { env } from "process";
configs

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/task/task.service.ts
> +  handlePullAttendanceCron() {
queue vs lastUpdatedAt

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
> -        if (overTime > 0) {
???

2022-09-06 06:40 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
filter items by type and status

2022-09-06 06:58 UTC, munkhgerel-gtn commented on prisma/schema.prisma
> +  isNormal  Boolean           @default(true)
хассан

2022-09-06 07:06 UTC, munkhgerel-gtn commented on src/modules/attendances/dtos/send_request.dto.ts
> +  @Matches(/^(APPROVED|DECLINED)$/, {
PENDING, CANCELED 2 -руу шилжүүлэхгүй байсан нь дээр гэж бодож байна.

2022-09-07 02:07 UTC, munkhgerel-gtn commented on src/modules/attendances/attendances.service.ts
> +const STARTHOUR: number = 16; // timeZone +8 үед 16 цаг нь 24 цагтай тэнцэнэ.
ашиглах шаардлаггүй болсон. toISOString() нь UTC -рүү шилжүүлэж байгаа

2022-09-07 02:08 UTC, munkhgerel-gtn commented on src/modules/auth/strategies/basic.strategy.ts
> +import { env } from "process";
config service ашигласан

2022-09-07 02:08 UTC, munkhgerel-gtn commented on src/modules/task/task.service.ts
> +  handlePullAttendanceCron() {
queue -ээр шийдсэн

2022-09-07 03:03 UTC, zolboo-gtn approved these changes

2022-09-07 03:03 UTC, zolboo-gtn commented on src/modules/attendances/attendances.service.ts
> +      if (
if_else хэрэгтэй эсэх?

2022-09-07 03:03 UTC, zolboo-gtn commented on src/modules/attendances/dtos/send_request.dto.ts
> +  @Matches(/^(APPROVED|DECLINED)$/, {
cancelled

2022-09-09 08:46 UTC, merged